### ISSUE TITLE
Any plans for a new non-pre-release of 2.0?

### ISSUE THREAD

**Issue by dsyrstad** [google/quiver-log#22]

**Comment by adambender** [comment]
Yup! We have just been working through pulling null-safety through all the code internal to Google. I hadn't updated the version to simplify some things internally. I will check with those running the migration and if they give me the greenlight I will make a formal 2.0 release.

**Comment by adambender** [comment]
Alright I was able to confirm with folks inside Google who depend on this library that going with a full release wont cause any problems so I will try to cut one in the next week or so.

**Comment by dsyrstad** [comment]
@adambender Great! Thank you!

**Comment by adambender** [comment]
I clearly failed in my initial promise, so let me not make this same
mistake again. It is something I'm trying to get to asap, but it's hard to
commit due to some fires at work. Will make another attempt this weekend :)

**Comment by dsyrstad** [comment]
Thanks @adambender!

**Comment by adambender** [comment]
I believe this is done. PTAL and let me know if anything got messed up!

**Comment by dsyrstad** [comment]
@adambender 2.0.0 is published, but pubspec.yaml has `analyzer` at ^2.0.0. The current version of `analyzer` is 3.3.1. This is causing a version conflict issue with one of my build runner dependencies (`mobx_codegen`). Perhaps you could update the `analyzer` dependency?  Here's the exact error:

```
Because mobx_codegen >=2.0.5 depends on analyzer ^3.0.0 and quiver_log >=2.0.0 depends on analyzer ^2.0.0, mobx_codegen >=2.0.5 is incompatible with quiver_log >=2.0.0.
So, because client_app depends on both quiver_log 2.0.0 and mobx_codegen ^2.0.5+2, version solving failed.
```

**Comment by adambender** [comment]
I was able to remove the dependency entirely so hopefully that makes it even easier. Version is now 2.0.1

**Comment by dsyrstad** [comment]
Great! Thanks @adambender! I tested it out and I'm using it now. The dependencies are all good.
